name: Daily Weather Email

on:
  schedule:
    - cron: '0 20 * * *'  # 毎日朝7時（JST）。UTC+9=JST→22:00(前日)
  workflow_dispatch:      # 手動実行も可能

jobs:
  send_weather:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run weather script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: |
          python main.py
